name: ukftbio
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - scipy
  - pandas
  - matplotlib
  - networkx
  - pip
  - pip:
    - plotly
    - biopython
    - pytest
